language: node_js
node_js:
  - "10"
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
before_install:
  - npm install -g npm@latest
install:
  - npm config set package-lock false
  - npm install
sudo: required
addons:
  chrome: stable # install chrome stable.
cache:
  yarn: true
  directories:
    - $HOME/.npm
before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      sudo: required
      addons:
        chrome: stable # install chrome stable.
      script:
        - npm run coverage
      after_success:
        - npm run coveralls
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release && chmod + ./config/deploy.sh
        'on':
          repo: naver/billboard.js
          branches:
            only:
              - master
              - next


